### ISSUE TITLE
Find RSS links

### ISSUE THREAD

**Issue by Partical777** [shung-yang/newsIntegration#14]
Write down the link to wiki

**Comment by shung-yang** [comment]
數位時代
Meet 創業小聚
T客邦
電腦王阿達
INSIDE
電獺少女
DQ 地球圖輯隊
癮科技 Cool3c
經理人
換日線
ShoppingDesign

**Comment by Partical777** [comment]
數位時代 : https://www.bnext.com.tw/rss
Meet 創業小聚 : https://meet.bnext.com.tw/rss
T客邦 : https://www.techbang.com/pages/subscribe
電腦王阿達 : https://www.kocpc.com.tw/feed
INSIDE : Not found
電獺少女 : Not found
DQ 地球圖輯隊 : https://dq.yam.com/rss/
癮科技 Cool3c : https://www.cool3c.com/rss (https://feeds.feedburner.com/cool3c-show)
經理人 : https://www.managertoday.com.tw/rss
換日線 : https://crossing.cw.com.tw/rss
ShoppingDesign : https://www.shoppingdesign.com.tw/rss
TechNews : https://technews.tw/tn-rss/
iThome : https://www.ithome.com.tw/rss

**Comment by Partical777** [comment]
已加入 Wiki
https://github.com/shung-yang/newsIntegration/wiki/RSS-info
